my_costmap:
  plugins: 
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: floor
  robot_base_frame: base_link
  footprint: [[0.4,0.4], [-0.45,0.4], [-0.45,-0.4], [0.4,-0.4]]
  #footprint: [[-0.65, 0], [-0.45, 0.45], [0, 0.65], [0.45, 0.45], [0.65, 0], [0.45, -0.45], [0, -0.65], [-0.45, -0.45]]
  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.1
  update_frequency: 5.0
  publish_frequency: 5.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: camera_link
      topic: scan
      data_type: LaserScan
      obstacle_range: 10.0
      raytrace_range: 10.0

      #sensor_frame: velodyne_link
      #topic: velodyne_points
      #data_type: PointCloud2
      #min_obstacle_height: 0.2
      
      marking: true
      clearing: true
  inflation_layer:
    inflation_radius: 1.3
  path_costmap:
    cost_path_width: 10.0